CREATE TABLE CUSTOMERS
(
USER_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
USER_NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
PHONE_NUMBER VARCHAR(20) NOT NULL,
COUNTRY VARCHAR(100),
ADDRESS VARCHAR(200),
CITY VARCHAR(100),
STATE VARCHAR(100),
ZIP_CODE INTEGER,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(USER_ID));

CREATE TABLE PROPERTY (
  PROPERTY_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  USER_ID BIGINT,
  PROPERTY_NAME VARCHAR(100),
  DESCRIPTION VARCHAR(1000),
  ADDRESS VARCHAR(200) NOT NULL,
  CITY VARCHAR(100) NOT NULL,
  STATE VARCHAR(100),
  ZIPCODE VARCHAR(20) NOT NULL,
  NUMBER_OF_ROOMS INTEGER,
  RENTAL_PRICE VARCHAR(20),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(USER_ID) REFERENCES CUSTOMERS(USER_ID));





